CREATE TABLE exhibition
(
    id    BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    date  TIMESTAMP NOT NULL,
    time  TIMESTAMP NOT NULL,
    movie BIGINT    NOT NULL,
    CONSTRAINT FK_MOVIE_EXHIBITION FOREIGN KEY (movie) REFERENCES movie (id)
);
